#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}{{if .Root}}:: Admin{{end}}'
terminal_background = 'p:t-background'


# First line starts
[[blocks]]

  # Left part of first line starts
  type = 'prompt'
  alignment = 'left'
  newline = true


  # Text block before path 
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:terminal-blue'
    background = 'transparent'
    #template = '▶ '
    template = ' '

  # Path info
  [[blocks.segments]]
    type = 'path'
	style = 'plain'
    foreground = 'p:terminal-magenta'
	background = 'transparent'
    folder_separator_icon = '/'
	home_icon = '~'
	template = '<b>{{ .Path }} | </b>'

	[blocks.segments.properties]
	  style = 'mixed'
	  mixed_threshold = 16

  # Git info
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:light-sky-blue'
	background = 'transparent'
    foreground_templates = [
	  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}',
	  '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}',
	  '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}',
	  '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}'
	]
    template = '{{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }} * {{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'

    [blocks.segments.properties]
      branch_icon = 'on  '
	  commit_icon = '@'
      fetch_status = true
	  fetch_upstream_icon = true
  # status module
  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'p:terminal-red'
	background = 'transparent'
	template = '{{ if .Env.LOW_COLOR_SUPPORT }} X{{ else }} {{ end }} '

# right side of first line starts
[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'
  # icons if language is present in wd 
  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:terminal-yellow'
	background = 'transparent'
    template = '{{ if .Env.LOW_COLOR_SUPPORT }}{{ .Full }}{{ else }} {{ .Full }}{{ end }}'

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:light-sky-blue'
	background = 'transparent'	
    template = '{{ if .Env.LOW_COLOR_SUPPORT }}{{ .Full }}{{ else }}ﳑ {{ .Full }}{{ end }}'

  # git status
  [[blocks.segments]]
    type = 'command'
    style = 'plain'
    foreground = 'p:white-blue'
	background = 'transparent'
	template = 'last commit: {{ .Output }}'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'zsh'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:white-blue'
    background = 'transparent'
    template = ' | took: {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

# second line begins
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
	foreground_templates = [
      "{{if gt .Code 0}}p:terminal-red{{end}}",
      "{{if eq .Code 0}}p:pistachio-green{{end}}",
    ]
	background = 'transparent'
    template = '{{ if .Env.LOW_COLOR_SUPPORT }}>{{ else }}❯{{ end }}'

[transient_prompt]
  foreground_templates = [
      "{{if gt .Code 0}}p:terminal-red{{end}}",
      "{{if eq .Code 0}}p:pistachio-blue{{end}}",
  ]
  background = 'transparent'
  template = '{{ if .Env.LOW_COLOR_SUPPORT }}>{{ else }}❯{{ end }} '

[secondary_prompt]
  foreground = 'p:terminal-blue'
  background = 'transparent'
  template = '{{ if .Env.LOW_COLOR_SUPPORT }}>>{{ else }}❯❯{{ end }} '

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'
