---
- name: arch-core.yml - base setup for arch
  hosts: arch
  become: no

  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:

# CONFIG - Pacman

    - name: Pacman - Enable color
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#Color$'
        line: 'Color'

    - name: Pacman - enable ParallelDownloads = 16
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: 'ParallelDownloads ='
        line: 'ParallelDownloads = 16'

    - name: Pacman - enable ILoveCandy
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#ILoveCandy$'
        line: 'ILoveCandy'

    - name: Pacman - enable VerbosePkgLists
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#VerbosePkgLists$'
        line: 'VerbosePkgLists'

    - name: Pacman - NoExtract for systemd home to fix a few warnings
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#NoExtract$'
        line: 'NoExtract = usr/lib/security/pam_systemd_home.so'

# CONFIG - nano

    - name: Nano - Enable color in config
      become: yes
      lineinfile:
        path: /etc/nanorc
        line: '{{ item.line }}'
      loop:
        - { line: 'include "/usr/share/nano/extra/*.nanorc"' }
        - { line: 'include "/usr/share/nano/*.nanorc"' }

# CONFIG - makepkg

    - name: makepkg - disable pkg compression
      become: yes
      lineinfile:
        path: /etc/makepkg.conf
        regexp: "PKGEXT='.pkg.tar.zst'"
        line: "PKGEXT='.pkg.tar'"

# PACKAGES - Upgrade

    - name: Full system upgrade via pacman
      become: yes
      pacman:
        update_cache: true
        upgrade: true


# PACKAGES - Setup

    - name: Setup base needed packages
      become: yes
      pacman:
        update_cache: yes
        name:
          - nano                         # editor
          - less                         # easy view utility
          - git                          # to clone github repos
          - base-devel                   # required packages for developer stuff
          - curl                         # download utility
          - wget                         # download utility
          - rsync                        # copy utility
          - bat                          # prettier cat
          - fastfetch                    # system info
          - btop                         # better resource monitor
          - lsd                          # better ls
          - zsh                          # better shell
          - zsh-autosuggestions          # self-explanatory
          - zsh-syntax-highlighting      # self-explanatory
          - zsh-history-substring-search # self-explanatory
          - zsh-completions              # self-explanatory
          - inxi                         # system info tool
          - pigz                         # faster gzip
          - pbzip2                       # faster bzip
          - fwupd                        # firmware update tool
          - amd-ucode                    # amd microcode
          - linux-firmware               # linux firmware
          - github-cli                   # better github integration
          - networkmanager               # self-explanatory
          - python3                      # self-explanatory
          - reflector                    # mirror update
        state: present

# OPTIMIZATION

    - name: fstab - change relatime to noatime
      become: yes
      replace:
        path: /etc/fstab
        regexp: 'relatime'
        replace: 'noatime'

# ZSH

    - name: change shell to zsh
      become: yes
      user:
        shell: /bin/zsh
        name: "{{ the_user }}"

    - name: copy zsh dotfile
      copy:
        src: user_home/.zshrc
        dest: /home/{{ the_user }}/.zshrc
        force: True
        owner: "{{ the_user }}"
        group: "{{ the_user }}"
        mode: u+rw,g+r,o--

    - name: copy p10k-main dotfile
      copy:
        src: user_home/.p10k-main.zsh
        dest: /home/{{ the_user }}/.p10k-main.zsh
        force: True
        owner: "{{ the_user }}"
        group: "{{ the_user }}"
        mode: u+rw,g+r,o--

    - name: copy p10k-portable dotfile
      copy:
        src: user_home/.p10k-portable.zsh
        dest: /home/{{ the_user }}/.p10k-portable.zsh
        force: True
        owner: "{{ the_user }}"
        group: "{{ the_user }}"
        mode: u+rw,g+r,o--

    - name: copy p10k dotfile
      copy:
        src: user_home/.p10k.zsh
        dest: /home/{{ the_user }}/.p10k.zsh
        force: True
        owner: "{{ the_user }}"
        group: "{{ the_user }}"
        mode: u+rw,g+r,o--

# User configuration - AUR preparation

#- name: Create the `aur_builder` user
#  become: yes
#  ansible.builtin.user:
#    name: aur_builder
#    create_home: yes
#    group: wheel

#- name: Allow the `aur_builder` user to run `sudo pacman` without a password
#  become: yes
#  ansible.builtin.lineinfile:
#    path: /etc/sudoers.d/11-install-aur_builder
#    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
#    create: yes
#    mode: 0644
#    validate: 'visudo -cf %s'

# AUR Setup

    - name: Install yay using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present

# PACKAGES - AUR packages setup

    - name: Install packages from AUR using yay
      community.general.pacman:
        update_cache: true
        name:
          - zsh-theme-powerlevel10k-git
        state: present
        executable: yay

