name: Ansible Quality Gates
on:
  push:
    branches: ["main", "master"]
    paths:
      - 'linux/ansible/**'
      - 'windows/**'
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Add fake .git dir
        run: mkdir -p "${{ github.workspace }}/linux/ansible/.git"
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.7.0
        with:
          working_directory: "${{ github.workspace }}/linux/ansible"
