name: ansible-lint
on:
  push:
    branches: ["main", "master"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.6.0
        with:
          working_directory: "${{ github.workspace }}/linux/ansible"
